---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: ran1-roskosb-info
  namespace: ran1-roskosb-info
  annotations:
    #agent-install.openshift.io/install-config-overrides: '{"networking":{"networkType":"OVNKubernetes"}}'
spec:
  apiVIP: 192.168.2.204
  #apiVIP: fd00:6:6:2052::98
  ingressVIP: 192.168.2.205
  #ingressVIP: fd00:6:6:2052::99
  clusterDeploymentRef:
    name: ran1-roskosb-info
  imageSetRef:
    name: openshift-v4.10.3
#  manifestsConfigMapRef:
#    name: cm-overrides-ran1-roskosb-info
  networking:
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      - cidr: fd01::/48
        hostPrefix: 64
    serviceNetwork:
      - 172.30.0.0/16
      - fd02::/112
    machineNetwork:
      - cidr: 192.168.2.0/24
  provisionRequirements:
    controlPlaneAgents: 3
    workerAgents: 0
#  proxy:
#    httpProxy: http://infra-registry.infra.cars.lab:3128
#    httpsProxy: http://infra-registry.infra.cars.lab:3128
#    noProxy: .cars.lab
  sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+utYpGWf0ei+J8M2TtX3YZmUQpTu1tLFI5Q/eQ189ucmpNMq8d/TjXr7BnaKoSQm0xxCT7a5OKnWCi713cVaCP6FJKczt1o4qV2MAlg35DZAJtgnWW05AvnYf345FYKMhod/LbCn8FWROPX3tssZURpTo8x8ylmEayPHZkU3pO7LK7gaRXpuVC/kzTmL5jneAcuUvVPH6RbGwm2FsAincT+LtX9/q55+W7CfjGWfqSq4TwyQlpvCMOsy99T86lEk3AWcou+ea7GN+lg8T7Cl5Y9GNBfD2CcB0rfTVVZXd+ZRZuvbDsxZ81gjeow9lcWF0xEymzccVD+R4PUxYlnHp broskos@broskos.remote.csb'
