---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: ran1-roskosb-info
  namespace: ran1-roskosb-info
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
