oc apply -f 06-namespace.yaml
oc apply -f 07-pullsecret.yaml
oc apply -f 08-aci.yaml
oc apply -f 09-clusterdeployment.yaml
oc apply -f 10-klusterletaddon.yaml
oc apply -f 11-managedcluster.yaml
oc apply -f 12-infraenv-ran1-roskosb-info.yaml
oc apply -f 13-nmstate-ran1-roskosb-info.yaml
oc apply -f 14-bmh-ran1-roskosb-info-cplane.yaml
